{"uuid": "1b00a670-461a-4880-a02e-2246fd08b160", "children": ["b3a17041-d06f-48fc-984b-cc6d739cfc12"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1741258553277, "stop": 1741258553277}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Administrator\\PycharmProjects\\Ecom-app\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Ecom-app\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Ecom-app\\test_cases\\conftest.py\", line 20, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1741258564123, "stop": 1741258564125}], "start": 1741258553277, "stop": 1741258564125}