{"uuid": "a33fce0d-b09d-4668-8338-01999ee1de75", "children": ["04e03335-0d4d-4136-a40a-8c8480f0b69a"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1741258541565, "stop": 1741258541565}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\Administrator\\PycharmProjects\\Ecom-app\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Ecom-app\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Administrator\\PycharmProjects\\Ecom-app\\test_cases\\conftest.py\", line 20, in log_on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1741258553255, "stop": 1741258553256}], "start": 1741258541565, "stop": 1741258553256}